// Seed for content-archetypes-from-md (story 012).
// Regenerated by `scripts/content-build` after T6.
import type { DropArchetype } from './drops';

export const HEAL_ORB: DropArchetype = {
  id: 'heal-orb',
  displayName: 'Heal Orb',
  radius: 0.35,
  ttlMs: 8000,
  effect: { kind: 'heal', amount: 1 },
  color: 0xff7aa8
};
