// TEMPORARY seed for story 013 T6.
// Regenerated by content-build after T9; do not edit by hand.
import type { PlayerSpawn } from '../session';
import type { PlayerArchetype } from './players';

export const HERO: PlayerArchetype = {
  id: 'hero',
  displayName: 'Hero',
  radius: 0.5,
  maxSpeed: 6,
  maxHp: 5
};

export const SANDBOX_PLAYER: PlayerSpawn = {
  position: { x: 0, y: 0 },
  radius: 0.5,
  maxSpeed: 6,
  maxHp: 1
};

export const TRAINING_PLAYER: PlayerSpawn = {
  position: { x: 0, y: 0 },
  radius: 0.5,
  maxSpeed: 6,
  maxHp: 5
};
