// Seed for content-archetypes-from-md (story 012).
// Regenerated by `scripts/content-build` after T5.
import type { WeaponArchetype } from './weapons';

export const PISTOL: WeaponArchetype = {
  id: 'pistol',
  displayName: 'Pistol',
  cooldownMs: 250,
  projectileSpeed: 24,
  projectileRadius: 0.1,
  projectileTtlMs: 2000,
  damage: 1,
  color: 0xffd76b
};
