// Seed for content-archetypes-from-md (story 012).
// Regenerated by `scripts/content-build` after T9.
import type { BossAudioMapping } from './AudioMappings';

export const BOSS_AUDIO_MAPPINGS: Readonly<Record<string, BossAudioMapping>> = Object.freeze({
  'slime-king': Object.freeze({
    fire: 'boss/boss-fireball',
    phaseChange: 'boss/boss-ahaha'
  })
});
