// Seed for content-archetypes-from-md (story 012).
// Regenerated by `scripts/content-build` after T7.
import type { WeaponAudioMapping } from './AudioMappings';

export const WEAPON_AUDIO_MAPPINGS: Readonly<Record<string, WeaponAudioMapping>> = Object.freeze({
  pistol: Object.freeze({ fire: 'weapons/pistol' }),
  shotgun: Object.freeze({ fire: 'weapons/shotgun' }),
  smg: Object.freeze({ fire: 'weapons/smg' }),
  sniper: Object.freeze({ fire: 'weapons/sniper' }),
  laser: Object.freeze({ fire: 'weapons/laser' })
});
