// TEMPORARY seed for story 013 T8.
// Regenerated by content-build after T11; do not edit by hand.
import type { SpriteVisualSpec } from './SpriteVisualSpec';

export const SLIME_KING_VISUAL: SpriteVisualSpec = {
  archetypeId: 'slime-king',
  image: '/assets/boss-03.png',
  sourceSizePx: { width: 682, height: 787 },
  worldSize: { width: 9.742857142857142, height: 11.242857142857142 },
  anchor: { x: 0.5, y: 0.5 }
};

export const BOSS_VISUAL_SPECS = [
  SLIME_KING_VISUAL
] as const satisfies ReadonlyArray<SpriteVisualSpec>;
