// TEMPORARY seed for story 013 T7.
// Regenerated by content-build after T10; do not edit by hand.
import type { SpriteVisualSpec } from './SpriteVisualSpec';

export const TRAINING_TARGET_VISUAL: SpriteVisualSpec = {
  archetypeId: 'training-target',
  image: '/assets/slime-05.png',
  sourceSizePx: { width: 388, height: 144 },
  worldSize: { width: 5.542857142857143, height: 2.057142857142857 },
  anchor: { x: 0.5, y: 0.5 }
};

export const SLIME_FAST_VISUAL: SpriteVisualSpec = {
  archetypeId: 'slime-fast',
  image: '/assets/slime-06.png',
  sourceSizePx: { width: 287, height: 285 },
  worldSize: { width: 4.1, height: 4.071428571428571 },
  anchor: { x: 0.5, y: 0.5 }
};

export const SLIME_TANK_VISUAL: SpriteVisualSpec = {
  archetypeId: 'slime-tank',
  image: '/assets/slime-04.png',
  sourceSizePx: { width: 290, height: 483 },
  worldSize: { width: 4.142857142857143, height: 6.9 },
  anchor: { x: 0.5, y: 0.5 }
};

export const ENEMY_VISUAL_SPECS = [
  TRAINING_TARGET_VISUAL,
  SLIME_FAST_VISUAL,
  SLIME_TANK_VISUAL
] as const satisfies ReadonlyArray<SpriteVisualSpec>;
