// TEMPORARY seed for story 013 T6.
// Regenerated by content-build after T9; do not edit by hand.
import type { SpriteVisualSpec } from './SpriteVisualSpec';

export const HERO_VISUAL: SpriteVisualSpec = {
  archetypeId: 'hero',
  image: '/assets/hero.png',
  sourceSizePx: { width: 294, height: 550 },
  worldSize: { width: 4.2, height: 7.857142857142857 },
  anchor: { x: 0.5, y: 0.5 }
};
